### ISSUE TITLE
Error in connection with mysql

### ISSUE THREAD

**Issue by geoffreychen831** [geoffreychen831/AABKoala#13]
![image](https://user-images.githubusercontent.com/36359703/93207605-ccffff80-f78d-11ea-863b-43d2c4d2ec6a.png)
This occurs when I run 'python manage.py runserver'
According to this post on StackOverFlow (https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded), this is because the newer version of mysql is using a new encryption method called caching_sha2_password, which is not supported by django yet. Therefore the solution is to set the password encryption to the old method by this line of code 

`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '<my-password>';`

**In our case, replace 'localhost' with '%'.**

Although I don't understand why this is not an issue on Yunning's end.

**Comment by Juncheng-Li** [comment]
Use native password method
